// SCROLL — comprehension digest (v1.4).
//
// Why: SCROLL's users include solopreneurs who are not engineers. An unattended loop that they
// only "press a button" on creates comprehension debt — passive delegation that erodes their grasp
// of what the agent actually did. After every run, SCROLL derives a short, human-readable digest
// from events.jsonl (no model call) so the owner can READ what happened — what was done, which
// dangerous tiers were touched, what it cost, and what still needs a human.
//
// Deterministic: it is a pure transform of the event stream. Language follows IDENTITY.language.
import fs from 'node:fs';
import path from 'node:path';

const L = {
  en: {
    title: 'Run digest', one_line: 'If you read one line', did: 'What it did', risky: 'Dangerous actions touched',
    cost: 'What it cost', attention: 'Needs your attention', none: 'nothing', tokens: 'tokens', verify: 'verification',
    approved: 'approved', blocked: 'BLOCKED — waiting for approval', denied: 'DENIED (grounding failed)',
    completed: 'completed', paused: 'paused', tasks: 'tasks', read: 'Generated by scroll — read this instead of just trusting the run.',
  },
  vi: {
    title: 'Tóm tắt lượt chạy', one_line: 'Nếu chỉ đọc một dòng', did: 'Đã làm gì', risky: 'Hành động nguy hiểm đã chạm',
    cost: 'Chi phí', attention: 'Cần bạn xem', none: 'không có', tokens: 'token', verify: 'kiểm chứng',
    approved: 'đã duyệt', blocked: 'BỊ CHẶN — chờ duyệt', denied: 'TỪ CHỐI (grounding fail)',
    completed: 'hoàn tất', paused: 'tạm dừng', tasks: 'việc', read: 'Sinh bởi scroll — đọc cái này thay vì chỉ tin lượt chạy.',
  },
};

export function readEvents(eventsPath) {
  if (!fs.existsSync(eventsPath)) return [];
  return fs.readFileSync(eventsPath, 'utf8').trim().split('\n').filter(Boolean)
    .map((l) => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean);
}

// Build the digest text from events. Returns a markdown string.
export function buildDigest(events, { language = 'en', metrics = null } = {}) {
  const t = L[language] || L.en;
  const completed = events.filter((e) => e.type === 'task_completed').map((e) => e.data.id);
  const dispatched = events.filter((e) => e.type === 'task_contract');
  const titleFor = (id) => { const d = dispatched.find((e) => e.data.taskId === id); return d ? (d.data.objective || id) : id; };

  // dangerous tiers touched: from permission_decision (v1.4) or legacy gate_* events
  const perms = events.filter((e) => e.type === 'permission_decision');
  const risky = perms.filter((e) => ['external_comm', 'financial', 'destructive'].includes(e.data.tier));
  const gatesLegacy = events.filter((e) => e.type === 'gate_requested');
  const blocked = events.filter((e) => e.type === 'gate_blocked' || (e.type === 'permission_decision' && e.data.decision === 'await'));
  const denied = events.filter((e) => e.type === 'grounding_failed' || (e.type === 'permission_decision' && e.data.decision === 'deny'));

  const m = metrics || (events.find((e) => e.type === 'completed' || e.type === 'paused')?.data?.metrics) || {};
  const status = events.some((e) => e.type === 'paused') ? t.paused : t.completed;
  const verify = events.find((e) => e.type === 'verification');

  const lines = [];
  lines.push(`# ${t.title}`);
  lines.push('');
  const oneLine = denied.length
    ? `${denied.length} action(s) ${t.denied}.`
    : blocked.length
      ? `${blocked.length} action(s) ${t.blocked}.`
      : `${status}: ${completed.length} ${t.tasks} · ${(m.billableTokenEquivalent ?? '?')} ${t.tokens} · $${m.costUsd ?? '?'}.`;
  lines.push(`**${t.one_line}:** ${oneLine}`);
  lines.push('');

  lines.push(`## ${t.did}`);
  if (completed.length) for (const id of completed) lines.push(`- ${id} — ${String(titleFor(id)).slice(0, 100)}`);
  else lines.push(`- ${t.none}`);
  lines.push('');

  lines.push(`## ${t.risky}`);
  const riskyAll = risky.length ? risky : gatesLegacy;
  if (riskyAll.length) {
    for (const e of riskyAll) {
      const tier = e.data.tier || e.data.risk || '?';
      const state = e.data.decision === 'deny' ? t.denied : (e.data.decision === 'await' || e.type === 'gate_blocked') ? t.blocked
        : e.data.approvedBeforeAction || e.data.decision === 'allow' ? t.approved : '?';
      lines.push(`- [${tier}] ${e.data.tool || e.data.gateId || e.data.taskId || ''} — ${state}`);
    }
  } else lines.push(`- ${t.none}`);
  lines.push('');

  lines.push(`## ${t.cost}`);
  lines.push(`- ${m.billableTokenEquivalent ?? '?'} ${t.tokens} · $${m.costUsd ?? '?'} · ${m.durationMs ?? '?'}ms · ${m.providerCalls ?? '?'} call(s)`);
  if (verify) lines.push(`- ${t.verify}: ${verify.data.passed ? 'PASS' : 'FAIL'}`);
  lines.push('');

  lines.push(`## ${t.attention}`);
  const att = [];
  for (const e of blocked) att.push(`- ${t.blocked}: ${e.data.gateId || e.data.tool || e.data.taskId || ''}`);
  for (const e of denied) att.push(`- ${t.denied}: ${e.data.tool || e.data.taskId || (e.data.missing || []).join(', ')}`);
  if (verify && verify.data.passed === false) att.push('- verification did not pass — review the output before trusting it');
  lines.push(att.length ? att.join('\n') : `- ${t.none}`);
  lines.push('');
  lines.push(`*${t.read}*`);
  return lines.join('\n');
}

// Write runDir/digest.md from the run's event stream. Returns the path.
export function writeDigest({ runDir, eventsPath, language = 'en', metrics = null } = {}) {
  const evs = readEvents(eventsPath || path.join(runDir, 'events.jsonl'));
  const md = buildDigest(evs, { language, metrics });
  const out = path.join(runDir, 'digest.md');
  fs.writeFileSync(out, md + '\n');
  return out;
}
