// SCROLL — the OUTER loop (v1.4). This is the "loop engineering" layer.
//
// `scroll run` is the INNER loop: one harnessed execution of a WORK.md.
// `LOOP.md` + `scroll loop` is the OUTER loop: the system that decides WHEN to start an inner
// loop, WHERE it finds work, and WHEN to stop — so an agent finds its own work, does it, verifies
// it, and remembers it, without a human prompting each turn. No engine: it rides `scroll run`,
// the filesystem, and the host scheduler (cron / scheduled-tasks / HEARTBEAT).
//
// Safety is non-negotiable: a LOOP.md MUST declare at least one stop condition, the outer loop
// NEVER escalates privilege (every action inside still goes through the permission matrix), and a
// digest is written after every inner run.
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { parseFrontmatter } from './scroll.js';
import { writeDigest } from './digest.js';
import { appendLedgerRow } from './ledger.js';

export function parseLoop(raw) {
  const { frontmatter, body } = parseFrontmatter(raw);
  return { frontmatter: frontmatter || {}, goal: body || '' };
}

// Validate a LOOP.md. A loop with no stop condition is refused — that is the whole safety point.
export function validateLoop(fm) {
  const errors = [];
  if (!fm || typeof fm !== 'object') { errors.push('LOOP.md has no frontmatter'); return errors; }
  if (!fm.id) errors.push('LOOP: missing id');
  if (!fm.controller) errors.push('LOOP: missing controller (one owner)');
  const sc = fm.stop_conditions || {};
  const hasStop = ['max_runs_per_day', 'budget_usd_per_day', 'until', 'max_runs'].some((k) => sc[k] != null)
    || (Array.isArray(sc.halt_on) && sc.halt_on.length > 0);
  if (!hasStop) errors.push('LOOP: stop_conditions must declare at least one limit (a loop with no stop condition is refused)');
  if (!fm.work_source) errors.push('LOOP: missing work_source');
  // v1.5 — new fields (all OPTIONAL; type-checked only when present → backward compatible).
  if (fm.max_tries_per_task != null && !(Number(fm.max_tries_per_task) >= 1)) errors.push('LOOP: max_tries_per_task must be a number >= 1');
  if (fm.ledger != null && typeof fm.ledger !== 'string') errors.push('LOOP: ledger must be a string (scheme://target)');
  if (fm.planner != null && typeof fm.planner !== 'string') errors.push('LOOP: planner must be a string (command)');
  return errors;
}

// Resolve the WORK for one iteration from the loop's work_source.
//   type: work_file  → reads an existing WORK.md (returns { workFile })
//   type: inline     → uses fm.work (a WORK.md string) written to a temp file
//   type: glob       → turns matched files into one task each (returns { workFile } generated)
function buildIterationWork(fm, cwd, iterDir) {
  const ws = fm.work_source || {};
  if (ws.type === 'work_file' && ws.query) {
    return { workFile: path.resolve(cwd, ws.query) };
  }
  if (ws.type === 'inline' && fm.work) {
    const p = path.join(iterDir, 'WORK.md');
    fs.writeFileSync(p, fm.work);
    return { workFile: p };
  }
  if (ws.type === 'glob' && ws.query) {
    const dir = path.resolve(cwd, path.dirname(ws.query));
    const re = new RegExp('^' + path.basename(ws.query).replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*') + '$');
    const matched = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => re.test(f)) : [];
    const tasks = matched.map((f, i) => [
      '```task',
      `id: item-${i + 1}`,
      `title: process ${f}`,
      'status: todo',
      `owner: ${fm.controller}`,
      `objective: Process the work item in ${f}.`,
      'output_format: decision-ready markdown',
      'boundaries: [stay within the item scope]',
      'blockedBy: []',
      i === matched.length - 1 ? 'final: true' : '',
      '```',
    ].filter(Boolean).join('\n'));
    const md = `---\ncontroller: ${fm.controller}\n---\n# generated by scroll loop\n\n${tasks.join('\n\n')}\n`;
    const p = path.join(iterDir, 'WORK.md');
    fs.writeFileSync(p, md);
    return { workFile: p, items: matched.length };
  }
  return { workFile: null };
}

function todayKey() { return new Date().toISOString().slice(0, 10); }

// Run the outer loop. `runWork` is injected so this stays testable without a provider.
//   opts: { cwd, once, maxRuns, dryRun, providerName, model, runWork, sleepMs }
export async function runLoop(loopFile, opts = {}) {
  const cwd = opts.cwd || process.cwd();
  const raw = fs.readFileSync(path.resolve(cwd, loopFile), 'utf8');
  const { frontmatter: fm, goal } = parseLoop(raw);
  const errors = validateLoop(fm);
  if (errors.length) { const e = new Error('invalid LOOP.md:\n  ' + errors.join('\n  ')); e.loopErrors = errors; throw e; }

  const loopDir = path.join(cwd, 'runs', `loop-${fm.id}`);
  fs.mkdirSync(loopDir, { recursive: true });
  const statePath = path.join(loopDir, 'state.json');
  const eventsPath = path.join(loopDir, 'loop-events.jsonl');
  let state = { day: todayKey(), runsToday: 0, spentToday: 0, totalRuns: 0 };
  if (fs.existsSync(statePath)) { try { state = JSON.parse(fs.readFileSync(statePath, 'utf8')); } catch { /* fresh */ } }
  if (state.day !== todayKey()) state = { day: todayKey(), runsToday: 0, spentToday: 0, totalRuns: state.totalRuns || 0 };

  const lemit = (type, data = {}) => {
    fs.appendFileSync(eventsPath, JSON.stringify({ ts: new Date().toISOString(), loop: fm.id, type, data }) + '\n');
    if (opts.verbose) console.log(`  loop:${type}`, data.reason || data.runId || '');
  };
  lemit('loop_started', { id: fm.id, controller: fm.controller, goal: goal.slice(0, 200) });

  // v1.5 — PLANNER (self-planning): run a command that generates the backlog BEFORE looping.
  if (fm.planner && !opts.dryRun) {
    try { execSync(String(fm.planner), { cwd, stdio: 'pipe' }); lemit('planner_ran', { planner: fm.planner }); }
    catch (e) { lemit('planner_failed', { planner: fm.planner, error: String(e.message || e).slice(0, 200) }); }
  }
  const MAXT = Math.max(1, Number(fm.max_tries_per_task ?? 3));   // v1.5 — try-budget PER-TASK (default 3)

  const sc = fm.stop_conditions || {};
  const runWork = opts.runWork; // injected (lib/runtime.js runWork) — keeps loop provider-free for tests
  if (!runWork) throw new Error('runLoop requires opts.runWork');

  const stopCheck = () => {
    if (sc.until && todayKey() > String(sc.until)) return `until ${sc.until} passed`;
    if (sc.max_runs != null && state.totalRuns >= Number(sc.max_runs)) return `max_runs ${sc.max_runs} reached`;
    if (sc.max_runs_per_day != null && state.runsToday >= Number(sc.max_runs_per_day)) return `max_runs_per_day ${sc.max_runs_per_day} reached`;
    if (sc.budget_usd_per_day != null && state.spentToday >= Number(sc.budget_usd_per_day)) return `budget_usd_per_day ${sc.budget_usd_per_day} reached`;
    return null;
  };

  const summary = { id: fm.id, iterations: 0, runs: [], stopped: null };
  const haltOn = new Set(Array.isArray(sc.halt_on) ? sc.halt_on : []);
  const maxIters = opts.once ? 1 : (opts.maxRuns != null ? Number(opts.maxRuns) : Number(sc.max_runs ?? sc.max_runs_per_day ?? 1));

  for (let i = 0; i < maxIters; i++) {
    const stop = stopCheck();
    if (stop) { summary.stopped = stop; lemit('loop_stopped', { reason: stop }); break; }

    const iterDir = path.join(loopDir, `iter-${state.totalRuns + 1}`);
    fs.mkdirSync(iterDir, { recursive: true });
    const { workFile, items } = buildIterationWork(fm, cwd, iterDir);
    if (!workFile || !fs.existsSync(workFile)) { summary.stopped = 'no work available'; lemit('loop_stopped', { reason: 'no work' }); break; }
    if (items === 0) { summary.stopped = 'work_source empty'; lemit('loop_idle', { reason: 'no items' }); break; }

    lemit('iteration_started', { n: state.totalRuns + 1, workFile: path.relative(cwd, workFile) });
    if (opts.dryRun) {
      summary.runs.push({ iteration: state.totalRuns + 1, dryRun: true, workFile: path.relative(cwd, workFile) });
      summary.iterations++; state.totalRuns++; state.runsToday++;
      try { appendLedgerRow(fm.ledger, cwd, loopDir, { ts: new Date().toISOString(), loop: fm.id, iteration: state.totalRuns, task: path.basename(workFile), status: 'dry-run', tries: 0, proof: '', digest: '' }); } catch { /* ignore */ }
      lemit('iteration_dry_run', { n: state.totalRuns });
      continue;
    }

    const runDir = path.join(iterDir, 'run');
    const budget = fm.budget || {};
    const caps = {};
    if (budget.per_run && budget.per_run.max_usd) caps.maxUsd = Number(budget.per_run.max_usd);

    // v1.5 — PER-TASK try-budget: up to MAXT attempts; stop early on pass (or gate_denied).
    let res, tries = 0, passed = false, gateDenied = false;
    for (tries = 1; tries <= MAXT; tries++) {
      res = await runWork({
        cwd, workFile, runDir,
        providerName: opts.providerName || 'auto', model: opts.model,
        language: fm.language, caps,
      });
      state.spentToday += (res.metrics && res.metrics.costUsd) || 0;
      gateDenied = res.status === 'paused' && haltOn.has('gate_denied');
      passed = !(res.verification && res.verification.passed === false);
      if (passed || gateDenied) break;
      if (tries < MAXT) lemit('task_retry', { n: state.totalRuns + 1, try: tries, of: MAXT });
    }
    state.runsToday++; state.totalRuns++; summary.iterations++;
    const triesDone = (passed || gateDenied) ? tries : MAXT;   // the for-loop overshoots tries by 1 when exhausted → clamp back to MAXT

    const digestPath = path.join(runDir, 'digest.md');
    const taskStatus = gateDenied ? 'gate_denied' : (passed ? 'done' : 'failed');
    // v1.5 — LEDGER: one row per output (pass OR fail). On fail, proof is STILL recorded (evidence of the attempt).
    const ledgerRow = {
      ts: new Date().toISOString(), loop: fm.id, iteration: state.totalRuns,
      task: path.basename(workFile), status: taskStatus, tries: triesDone,
      proof: res.proof ? path.relative(cwd, path.resolve(cwd, String(res.proof))) : '',
      digest: fs.existsSync(digestPath) ? path.relative(cwd, digestPath) : '',
    };
    try { appendLedgerRow(fm.ledger, cwd, loopDir, ledgerRow); lemit('ledger_row', ledgerRow); }
    catch (e) { lemit('ledger_failed', { error: String(e.message || e).slice(0, 160) }); }

    summary.runs.push({ iteration: state.totalRuns, status: res.status, taskStatus, verify: passed, tries: triesDone, proof: ledgerRow.proof || null, digest: ledgerRow.digest || null });
    lemit('iteration_completed', { n: state.totalRuns, status: taskStatus, verify: passed, tries: triesDone, costUsd: res.metrics?.costUsd });
    fs.writeFileSync(statePath, JSON.stringify(state, null, 2));

    // v1.5 — FAIL-CONTINUE: gate_denied → halt immediately. verify_fail (after exhausting MAXT) → halt ONLY if 'verify_fail' ∈ halt_on; otherwise CONTINUE to the next task.
    if (gateDenied) { summary.stopped = 'gate_denied'; lemit('loop_halted', { reason: summary.stopped }); break; }
    if (!passed && haltOn.has('verify_fail')) { summary.stopped = `verify_fail after ${triesDone} tries`; lemit('loop_halted', { reason: summary.stopped }); break; }
    if (!opts.once && i < maxIters - 1 && opts.sleepMs) await new Promise((r) => setTimeout(r, opts.sleepMs));
  }

  fs.writeFileSync(statePath, JSON.stringify(state, null, 2));
  lemit('loop_finished', { iterations: summary.iterations, stopped: summary.stopped });
  summary.eventsPath = eventsPath;
  summary.loopDir = loopDir;
  return summary;
}
